# build stage
FROM node:10.15.1-alpine as build-stage
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install
COPY public public
COPY src src
RUN yarn run build

# production stage
FROM nginx:1.15.5-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]